### ISSUE TITLE
Consider replacing outdated docker image from `relintdockerhubpushbot` with new image from `cloudfoundry`

### ISSUE THREAD

**Issue by ctlong** [cloudfoundry/capi-ci#29]
Highly recommend that y'all consider switching from the unmaintained `relintdockerhubpushbot/cf-deployment-concourse-tasks` image to the maintained `cloudfoundry/cf-deployment-concourse-tasks` image. The image location was moved around two years ago, and the old image hasn't been updated since then.

I see that the old image is used in many tasks within this repo, for example:
https://github.com/cloudfoundry/capi-ci/blob/d96b8d8533eb913750e6a72c59a4778003eac2ef/ci/bosh/upload-release.yml#L6

**Comment by sethboyles** [comment]
thanks for the heads up!  Too bad we didn't heed your warning and waited for the pipeline to break 😓
