### ISSUE TITLE
Kiki is not actually testing that migrations are backward compatible

### ISSUE THREAD

**Issue by sethboyles** [cloudfoundry/capi-ci#49]
In [this commit](https://github.com/cloudfoundry/capi-ci/commit/63016bb4baac3de604f8c08cbdb358d03f1f5a8d), the kiki `apply_latest_migrations.sh` script was switched from using proxychains to apply migrations to using `bosh ssh`.

This unfortunately defeats the purpose of the kiki environment.  From `capi-ci` README.md:

> Kiki starts with an older version of cf-deployment. It then runs the new migrations, but keeps the old cloud controller code. This catches any backwards-incompatible migrations. This is important because cloud controller instances do rolling upgrades. For example: if you write a migration that drops a table, old CC instances that depend on that table existing will crash during the rolling deploy.

The script previously used [proxychains](https://github.com/cloudfoundry/capi-ci/commit/6ee95aacac32cca8e205b8905cbad999d26f3b80) (or [tsocks](https://github.com/cloudfoundry/capi-ci/commit/2c6882ee68f5b8804ef8dfa68caeb75cc8b3659c#diff-a367f879f11403ba89ac31efb886e9993c70efd0ab949818f1db45e15964270aR90-R93) in the original commit) as a way of running migrations from the concourse VM's local version of capi-release (which is newer than what's deployed) against the foundation's database, so that newer migrations are run WHILE the foundation is still using code from an older version.

Using `bosh ssh` just runs the migrations that are already deployed to the VM (i.e. no new migrations are run).  So since this change kiki, has not been actually testing that new migrations are backward compatible.

## What to do

Make the `apply_latest_migrations` script actually apply latest migrations. 

I think we have a few options:

1. We can revert back to using proxychains.  This may be hard because we apparently can't [edit /etc/hosts](https://github.com/cloudfoundry/capi-ci/commit/2c6882ee68f5b8804ef8dfa68caeb75cc8b3659c#diff-a367f879f11403ba89ac31efb886e9993c70efd0ab949818f1db45e15964270aR80) with [this change to using registry-image resource instead of docker-image](https://github.com/cloudfoundry/runtime-ci/commit/735acf14a8d7d1bb89fe429560e5ca58ab2cce9f#diff-edfda94f43fc1dc02ff6e38c064be327a515145da3d583f75bbd824b233fce7a) (and is how we stumbled upon this issue)

2. Maybe we can look into using [bosh scp](https://bosh.io/docs/cli-v2/#scp) to copy the new capi-release (perhaps in /tmp) to the vm and then using `bosh ssh`.

3. Some other way?

**Comment by philippthun** [comment]
I've updated the [apply_latest_migrations](https://github.com/cloudfoundry/capi-ci/blob/main/ci/migrations/apply_latest_migrations.sh) task.

What the script now does:
1. Upload capi-release (release candidate) tarball with `bosh scp`.
2. Unpack (parts of) the tarball (`bosh ssh`).
3. Copy the `db` folder (with `migrations` and `helpers` subfolders) over to `/var/vcap/packages/cloud_controller_ng` (`bosh ssh`).
4. Run `bundle exec rake db:migrate` (`bosh ssh`).

I think as long as the first rule [how to write migrations](https://github.com/cloudfoundry/cloud_controller_ng/tree/main/db/migrations#rules-when-writing-migrations) is followed - **Do not use any Cloud Controller code** - this approach might be sufficient.

**Comment by philippthun** [comment]
@sethboyles - Do you think we can close this issue, i.e. do you agree that my changes to `apply_latest_migrations` are "good enough"?
